apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels: 
    app: cbz-app
spec:
  replicas: 3
  template:
    metadata: 
      labels:
        app: cbz-app
    spec:
      containers:
        - name: my-c
          image: httpd
          ports:
            - containerPort: 80
  selector:
    app: cbz-app

---

#apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: cbz-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: cbz-app


