apiVersion: apps/v1                 
kind: ReplicaSet
metadata:
  name: my-rs
  labels: 
    app: rs-app
spec:
  replicas: 4
  template:
    metadata: 
      labels:
        app: rs-app
    spec:
      containers:
        - name: my-c
          image: httpd
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: rs-app
    matchExpressions:
      - {key: app, operator: In, values: [cbz-app, rs-app]}
---

apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: cbz-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: rs-app


